[package]
name = "k-means-gpu-cli"
version = "0.1.0"
edition = "2021"
authors = ["Benoit Vermont <redwarp@gmail.com>"]
description = "Command line tool to use the k-means-gpu library"
readme = "README.md"
license = "MIT"
repository = "https://github.com/redwarp/k-means-gpu"
keywords = ["image", "wgpu", "k-means"]
categories = ["graphics", "multimedia::images", "command-line-utilities"]
exclude = ["gfx", ".vscode"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
image = "0.24"
anyhow = "1.0"
pollster = "0.2"
clap = { version = "4.0", features = ["cargo", "derive"] }
log = "0.4"
env_logger = "0.9"
regex = "1.5"
k-means-gpu = { path = "../core" }
